import { type ButtonHTMLAttributes, type ReactNode } from 'react';
import { ArrowLeft, ChevronRight, X } from 'lucide-react';

export function Button({ children, variant = 'primary', className = '', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'ghost' | 'danger' | 'dark' }) {
  return <button {...props} className={`rounded-xl px-4 py-3 text-sm font-semibold transition-transform active:scale-[.98] disabled:cursor-not-allowed disabled:opacity-40 ${variant === 'primary' ? 'bg-[#f6b954] text-[#161824]' : variant === 'danger' ? 'bg-[#9f3f4f] text-[#fff3e6]' : variant === 'ghost' ? 'bg-transparent text-[#b9bdca] hover:bg-white/5' : 'bg-[#292d43] text-[#f3e8d2]'} ${className}`} />;
}
export function AppHeader({ title, subtitle, onBack }: { title: string; subtitle?: string; onBack: () => void }) {
  return <header className="flex items-center gap-3 px-5 pb-4 pt-4"><Button variant="ghost" className="!p-2" onClick={onBack} data-testid="button-back"><ArrowLeft size={19} /></Button><div><h1 className="font-[Syne] text-lg font-bold tracking-tight">{title}</h1>{subtitle && <p className="mono text-[9px] uppercase tracking-[.16em] text-[#8b90a3]">{subtitle}</p>}</div></header>;
}
export function Panel({ children, className = '' }: { children: ReactNode; className?: string }) { return <section className={`glass rounded-2xl p-4 ${className}`}>{children}</section>; }
export function SectionTitle({ children, action }: { children: ReactNode; action?: ReactNode }) { return <div className="mb-3 flex items-center justify-between"><h2 className="mono text-[10px] font-medium uppercase tracking-[.18em] text-[#9ca1b0]">{children}</h2>{action}</div>; }
export function Metric({ label, value, color = '#f6b954' }: { label: string; value: string | number; color?: string }) { return <div><div className="mb-1 flex items-center justify-between"><span className="text-[10px] text-[#979bad]">{label}</span><strong className="mono text-[11px]" style={{ color }}>{value}</strong></div><div className="stat-track"><div className="stat-fill" style={{ width: `${typeof value === 'number' ? Math.min(value, 100) : 45}%`, background: color }} /></div></div>; }
export function Choice({ title, detail, onClick, disabled, risk }: { title: string; detail: string; onClick: () => void; disabled?: boolean; risk?: string }) { return <button disabled={disabled} onClick={onClick} data-testid={`button-choice-${title.toLowerCase().replaceAll(' ', '-')}`} className="group flex w-full items-center justify-between border-b border-white/[.07] py-3 text-left last:border-0"><span><span className="block text-sm font-medium text-[#eee6d7]">{title}</span><span className="mt-1 block text-[11px] leading-4 text-[#9297a8]">{detail}</span>{risk && <span className="mt-1 inline-block mono text-[9px] uppercase tracking-wider text-[#db7b86]">{risk}</span>}</span><ChevronRight size={16} className="shrink-0 text-[#63697b] transition-transform group-hover:translate-x-1" /></button>; }
export function Modal({ title, body, risk, primary, secondary, onPrimary, onSecondary, onClose }: { title: string; body: string; risk?: string; primary: string; secondary?: string; onPrimary?: () => void; onSecondary?: () => void; onClose: () => void }) { return <div className="fixed inset-0 z-30 flex items-end justify-center bg-[#070810]/75 p-4 backdrop-blur-sm sm:items-center"><div className="animate-rise w-full max-w-[390px] rounded-3xl border border-white/10 bg-[#1a1d30] p-5 shadow-2xl"><div className="mb-4 flex items-start justify-between"><h2 className="font-[Syne] text-xl font-bold">{title}</h2><Button variant="ghost" className="!p-1" onClick={onClose} data-testid="button-close-modal"><X size={18} /></Button></div><p className="text-sm leading-6 text-[#b4b7c3]">{body}</p>{risk && <div className="mt-4 rounded-xl border border-[#b65f69]/30 bg-[#542d3a]/30 px-3 py-2 mono text-[10px] uppercase tracking-[.14em] text-[#e38b8e]">Risk profile · {risk}</div>}<div className="mt-6 grid grid-cols-2 gap-2"><Button onClick={onPrimary ?? onClose} data-testid="button-modal-primary">{primary}</Button>{secondary && <Button variant="dark" onClick={onSecondary ?? onClose} data-testid="button-modal-secondary">{secondary}</Button>}</div></div></div>; }