import { useState, type ReactNode } from 'react';
import { GameProvider, useGame, type AppName } from './state/game';
import { AppHeader, Button, Choice, Metric, Modal, Panel, SectionTitle } from './components/primitives';
import {
  Activity, Aperture, ArrowUpRight, Award, Banknote, Bike, BriefcaseBusiness, Building2, Camera,
  ChartNoAxesCombined, Check, Clapperboard, CloudSun, Coins, Crown, FileKey2, Film, Gavel, Heart,
  House, Landmark, LockKeyhole, MapPin, Megaphone, Moon, Newspaper, PartyPopper, PiggyBank, Play,
  Radio, ReceiptText, ScanFace, Shield, Shirt, Smartphone, Sparkles, Star, Stethoscope, TrendingUp,
  UserRound, Users, Video, WalletCards, Wifi, Youtube, Zap,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

const money = (n: number) => `${n < 0 ? '-' : ''}$${Math.abs(Math.round(n)).toLocaleString()}`;
const compact = (n: number) => n > 999999 ? `${(n / 1000000).toFixed(1)}M` : n > 999 ? `${(n / 1000).toFixed(1)}K` : n.toString();

type AppMeta = { id: AppName; name: string; note: string; icon: LucideIcon; color: string; group: string };
const apps: AppMeta[] = [
  ['instafame','InstaFame','social',Camera,'#c46d78','SIGNAL'], ['viewtube','ViewTube','video',Youtube,'#a94d5b','SIGNAL'],
  ['chirp','Chirp','hot takes',Megaphone,'#7680bc','SIGNAL'], ['reeltok','ReelTok','trends',Activity,'#57a1a2','SIGNAL'],
  ['studio','Studio','career',Clapperboard,'#c39155','CAREER'], ['jetsetter','JetSetter','travel',MapPin,'#628ca1','LIFE'],
  ['bizmogul','BizMogul','ventures',TrendingUp,'#8a6fa8','MONEY'], ['oscaraura','OscarAura','awards',Award,'#bc9851','CAREER'],
  ['justilaw','JustiLaw','legal',Gavel,'#64728d','RISK'], ['darkos','DarkOS','fictional',LockKeyhole,'#684f6c','RISK'],
  ['glowclinic','GlowClinic','appearance',ScanFace,'#bc6d88','LIFE'], ['rayamatch','RayaMatch','romance',Heart,'#a45b76','LIFE'],
  ['billionestate','BillionEstate','security',Building2,'#7d7770','MONEY'], ['fanpulse','FanPulse','community',Users,'#5e8194','SIGNAL'],
  ['starbank','StarBank','cashflow',Landmark,'#bf9b58','MONEY'], ['marketwatch','MarketWatch','portfolio',ChartNoAxesCombined,'#5e9d91','MONEY'],
  ['cryptovault','CryptoVault','volatile',Coins,'#a778bd','MONEY'], ['rentcontrol','RentControl','housing',House,'#b87d68','MONEY'],
  ['netstream','NetStream','streaming',Film,'#b86574','CAREER'], ['maxplus','MaxPlus','streaming',Play,'#6c8cb3','CAREER'],
  ['boxoffice','BoxOffice','receipts',ReceiptText,'#c79b5e','CAREER'], ['prcommand','PRCommand','crisis desk',Radio,'#ca7782','RISK'],
  ['ndavault','NDA Vault','quiet files',FileKey2,'#8b83ad','RISK'], ['rehab','Rehab','reset',Stethoscope,'#6fa18f','LIFE'],
  ['boxingnight','Boxing Night','relevance',Bike,'#bd725e','CAREER'], ['deepfakedesk','Deepfake Desk','synthetic risk',ScanFace,'#917eb4','RISK'],
  ['swatshield','SwatShield','security',Shield,'#7a9baf','RISK'], ['botfarm','BotFarm','fictional reach',Wifi,'#a27ca7','RISK'],
  ['trendlab','TrendLab','forecast',Sparkles,'#7d9a77','SIGNAL'], ['paparazzi','Paparazzi','pressure',Aperture,'#a27965','RISK'],
  ['newswire','NewsWire','headlines',Newspaper,'#ba8e68','SIGNAL'], ['contracts','Contracts','offers',BriefcaseBusiness,'#7c9ba3','CAREER'],
  ['talenthouse','TalentHouse','roster',Users,'#9c7ab4','CAREER'], ['healthos','HealthOS','vitals',Stethoscope,'#659e91','LIFE'],
  ['sleeplab','SleepLab','recovery',Moon,'#687ca8','LIFE'], ['nutrition','Nutrition','fuel',Zap,'#b19763','LIFE'],
  ['styledesk','StyleDesk','wardrobe',Shirt,'#ad7188','LIFE'], ['autodrive','AutoDrive','garage',Bike,'#7e8f9b','LIFE'],
  ['travelsafe','TravelSafe','itinerary',CloudSun,'#6e9caa','LIFE'], ['taxoffice','TaxOffice','quarterly',ReceiptText,'#9f9171','MONEY'],
  ['charity','Charity','giving',PiggyBank,'#769e8b','LIFE'], ['fanclub','FanClub','members',Users,'#b47780','SIGNAL'],
  ['eventpass','EventPass','calendar',PartyPopper,'#b08a65','LIFE'], ['securechat','SecureChat','private',LockKeyhole,'#758aa8','RISK'],
].map(([id,name,note,icon,color,group]) => ({ id: id as AppName, name: name as string, note: note as string, icon: icon as LucideIcon, color: color as string, group: group as string }));

function App() { return <GameProvider><StarOS /></GameProvider>; }

function StarOS() {
  const { state, dispatch } = useGame();
  return <main className="star-app phone-noise text-[#eee6d7]"><div className="phone-frame"><div className="phone-inner">
    {state.activeApp === 'home' ? <Home /> : <AppView />}
    {state.modal && <Modal {...state.modal} onClose={() => dispatch({ type: 'CLOSE_MODAL' })} onPrimary={state.modal.onPrimary ? () => { if (state.modal?.onPrimary) dispatch(state.modal.onPrimary); dispatch({ type: 'CLOSE_MODAL' }); } : undefined} onSecondary={state.modal.onSecondary ? () => { if (state.modal?.onSecondary) dispatch(state.modal.onSecondary); dispatch({ type: 'CLOSE_MODAL' }); } : undefined} />}
  </div></div></main>;

  function Home() {
    const [page, setPage] = useState(0);
    const [showProfile, setShowProfile] = useState(false);
    const groups = ['ALL', 'SIGNAL', 'CAREER', 'MONEY', 'RISK', 'LIFE'];
    const filtered = page === 0 ? apps : apps.filter(a => a.group === groups[page]);
    return <div className="min-h-full bg-[linear-gradient(180deg,#121526_0%,#0e101c_100%)] pb-5">
      <StatusBar />
      <div className="px-5 pt-3">
        <div className="flex items-start justify-between"><div><p className="mono text-[10px] uppercase tracking-[.2em] text-[#8d92a4]">StarOS / week {state.week}</p><h1 className="mt-1 font-[Syne] text-3xl font-bold tracking-[-.04em]">Make them<br /><span className="text-[#f6b954]">remember you.</span></h1></div><button onClick={() => setShowProfile(!showProfile)} data-testid="button-open-profile" className="grid h-11 w-11 place-items-center rounded-full border border-[#f6b954]/30 bg-[#2b2b40] text-[#f6b954]"><UserRound size={19} /></button></div>
        {showProfile && <Panel className="animate-rise mt-4"><SectionTitle>Player dossier</SectionTitle><div className="grid grid-cols-4 gap-2 text-center"><div><strong className="block font-[Syne] text-lg">{state.age}</strong><span className="text-[9px] text-[#9297a8]">age</span></div><div><strong className="block font-[Syne] text-lg">{state.tier}</strong><span className="text-[9px] text-[#9297a8]">tier</span></div><div><strong className="block font-[Syne] text-lg">{state.city}</strong><span className="text-[9px] text-[#9297a8]">base</span></div><div><strong className="block font-[Syne] text-lg">{state.prCredits}</strong><span className="text-[9px] text-[#9297a8]">PR credits</span></div></div></Panel>}
        <div className="mt-7 grid grid-cols-3 gap-2"><TopStat label="CASH" value={money(state.money)} color="#f6b954" /><TopStat label="FAME" value={`${state.fame}`} color="#db7b86" /><TopStat label="REACH" value={compact(state.followers)} color="#81b8b0" /></div>
        <div className="mt-3 grid grid-cols-2 gap-3"><Metric label="Reputation" value={state.reputation} color="#c8a0da" /><Metric label="Burnout" value={state.burnout} color="#d77f89" /></div>
      </div>
      <div className="mt-7 px-5"><div className="mb-3 flex items-center justify-between"><SectionTitle>Orbit</SectionTitle><span className="mono text-[9px] text-[#696f80]">{apps.length} SERVICES</span></div><div className="mb-4 flex gap-1 overflow-x-auto pb-1">{groups.map((g, i) => <button key={g} onClick={() => setPage(i)} data-testid={`button-filter-${g.toLowerCase()}`} className={`shrink-0 rounded-full px-3 py-1.5 mono text-[9px] tracking-wider ${page === i ? 'bg-[#f6b954] text-[#171925]' : 'bg-[#20243a] text-[#8e93a5]'}`}>{g}</button>)}</div><div className="grid grid-cols-4 gap-x-2 gap-y-5">{filtered.map((a, i) => <button key={a.id} onClick={() => dispatch({ type: 'OPEN_APP', app: a.id })} data-testid={`button-open-${a.id}`} className="animate-rise group text-center"><span className="mx-auto grid h-[52px] w-[52px] place-items-center rounded-[17px] border border-white/10 shadow-lg transition-transform group-active:scale-95" style={{ background: `linear-gradient(145deg, ${a.color}, #24263a)` }}><a.icon size={21} strokeWidth={1.7} /></span><span className="mt-2 block text-[10px] font-medium text-[#dbd7d1]">{a.name}</span><span className="mt-0.5 block mono text-[8px] uppercase tracking-wider text-[#6f7488]">{a.note}</span></button>)}</div></div>
      <div className="mt-7 px-5"><SectionTitle action={<span className="mono text-[9px] text-[#696f80]">LIVE FEED</span>}>Signal</SectionTitle><div className="scan-line overflow-hidden rounded-xl border border-white/[.07] bg-[#181b2b] p-3"><p className="flex gap-2 text-xs leading-5 text-[#b7bac6]"><Zap size={14} className="mt-0.5 shrink-0 text-[#f6b954]" />{state.eventLog[0]}</p></div></div>
      <div className="mt-7 px-5"><Button className="flex w-full items-center justify-center gap-2 py-4 text-base" onClick={() => dispatch({ type: 'ADVANCE_WEEK' })} data-testid="button-advance-week"><span>Advance week</span><ArrowUpRight size={18} /></Button><p className="mt-2 text-center mono text-[9px] uppercase tracking-[.16em] text-[#646a7c]">one tap • consequences compound</p></div>
      <div className="mt-7 grid grid-cols-4 border-t border-white/[.07] px-7 pt-4 text-center"><Dock icon={WalletCards} label="Money" value={money(state.money)} /><Dock icon={Crown} label="Tier" value={state.tier} /><Dock icon={Shield} label="Risk" value={`${state.cancelHeat}%`} /><Dock icon={House} label="Rent" value={money(state.rent)} /></div>
    </div>;
  }
  function StatusBar() { return <div className="flex items-center justify-between px-5 pt-4 text-[10px] text-[#c1c0c0]"><span className="mono">09:41</span><span className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#f6b954]" />STAROS <span className="mono">▮▮▮</span></span></div>; }
  function AppView() { const common = { onBack: () => dispatch({ type: 'BACK_HOME' }) }; switch (state.activeApp) {
    case 'instafame': return <SocialApp {...common} title="InstaFame" kind="story" />;
    case 'viewtube': return <SocialApp {...common} title="ViewTube" kind="video" />;
    case 'chirp': return <SocialApp {...common} title="Chirp" kind="hot take" />;
    case 'reeltok': return <SocialApp {...common} title="ReelTok" kind="trend" />;
    case 'studio': return <Studio {...common} />; case 'starbank': case 'marketwatch': case 'cryptovault': case 'rentcontrol': return <MoneyApp {...common} />;
    case 'prcommand': case 'ndavault': case 'rehab': case 'deepfakedesk': case 'swatshield': case 'botfarm': return <RiskApp {...common} />;
    case 'netstream': case 'maxplus': case 'boxoffice': case 'contracts': case 'talenthouse': case 'boxingnight': return <CareerApp {...common} />;
    default: { const meta = apps.find(a => a.id === state.activeApp); return meta ? <AppDetail {...common} meta={meta} /> : null; }
  } }
}

function Status({ children }: { children?: ReactNode }) { const { state } = useGame(); return <div className="flex items-center justify-between px-5 pt-4"><span className="mono text-[9px] text-[#858a9b]">STAROS / {state.city.toUpperCase()}</span><span className="flex items-center gap-1 mono text-[9px] text-[#f6b954]">{money(state.money)} <span className="text-[#6d7384]">•</span> W{state.week}</span>{children}</div>; }
function Shell({ title, subtitle, children, onBack }: { title: string; subtitle: string; children: ReactNode; onBack: () => void }) { return <div className="min-h-full bg-[#111322] pb-8"><Status /><AppHeader title={title} subtitle={subtitle} onBack={onBack} /><div className="space-y-4 px-5">{children}</div></div>; }
function TopStat({ label, value, color }: { label: string; value: string; color: string }) { return <div className="rounded-xl border border-white/[.07] bg-[#1a1d2d] px-3 py-2"><span className="mono text-[8px] tracking-[.16em] text-[#7c8191]">{label}</span><strong className="mt-1 block font-[Syne] text-lg" style={{ color }}>{value}</strong></div>; }
function Dock({ icon: Icon, label, value }: { icon: LucideIcon; label: string; value: string }) { return <div><Icon size={15} className="mx-auto mb-1 text-[#777d92]" /><span className="block text-[10px] text-[#828697]">{label}</span><span className="mt-0.5 block truncate px-1 mono text-[9px] text-[#d9c08b]">{value}</span></div>; }

function SocialApp({ onBack, title, kind }: { onBack: () => void; title: string; kind: string }) {
  const { state, dispatch } = useGame(); const [tab, setTab] = useState('signal');
  return <Shell title={title} subtitle={`${kind} / algorithm control`} onBack={onBack}>
    <Panel className="bg-[linear-gradient(145deg,#332b3d,#1a1d2e)]"><div className="flex items-center justify-between"><div><span className="mono text-[9px] uppercase tracking-widest text-[#d28d9e]">command center</span><h2 className="mt-2 font-[Syne] text-2xl font-bold">{state.algorithmFavor > 65 ? 'The feed is listening.' : 'The feed is undecided.'}</h2></div><Smartphone className="text-[#e39aaa]" size={36} strokeWidth={1} /></div><div className="mt-5 grid grid-cols-3 gap-2"><Metric label="favor" value={state.algorithmFavor} color="#df9a81" /><Metric label="burnout" value={state.contentBurnout} color="#b9788e" /><Metric label="cancel" value={state.cancelHeat} color="#d77f89" /></div></Panel>
    <div className="flex gap-3 border-b border-white/[.07]">{['signal','scandal'].map(t => <button key={t} onClick={() => setTab(t)} data-testid={`button-social-tab-${t}`} className={`pb-3 text-xs capitalize ${tab === t ? 'border-b-2 border-[#f6b954] text-[#f6b954]' : 'text-[#777d8d]'}`}>{t}</button>)}</div>
    {tab === 'signal' ? <Panel><SectionTitle>Publish a signal</SectionTitle><Choice title="Candid / disclosed" detail="Trust compounds slower. It does not usually explode." onClick={() => dispatch({ type: 'POST_FEED', kind: 'honest' })} /><Choice title="Gambling sponsor / #ad" detail="$3,200 now. Audience trust and cancel heat later." risk="brand risk / +22 heat" onClick={() => dispatch({ type: 'BRAND_DEAL', brand: 'Betting house' })} /><Choice title="Unfiltered confession" detail="The algorithm rewards the wound, then asks for another." risk="burnout +11" onClick={() => dispatch({ type: title === 'ViewTube' ? 'UPLOAD' : 'POST_FEED', mode: 'raw', kind: 'thirst trap' } as never)} /></Panel> : <Panel><SectionTitle>Cancel Culture 2.0</SectionTitle><Choice title="Answer the AI deepfake" detail="Name the synthetic clip, show the correction, keep the tone plain." onClick={() => dispatch({ type: 'APP_LOOP', app: 'deepfakedesk', choice: 'report' })} /><Choice title="Perform the apology" detail="A perfect apology travels further than the original scandal." risk="authenticity risk" onClick={() => dispatch({ type: 'APOLOGY', fake: true })} /><Choice title="Correct and log off" detail="Protect the nervous system. The timeline will move on." onClick={() => dispatch({ type: 'APOLOGY', fake: false })} /></Panel>}
  </Shell>;
}

function MoneyApp({ onBack }: { onBack: () => void }) { const { state, dispatch } = useGame(); const app = state.activeApp; const title = apps.find(a => a.id === app)?.name ?? 'Money'; return <Shell title={title} subtitle="cashflow / volatility / receipts" onBack={onBack}><Panel className="bg-[linear-gradient(145deg,#263b39,#191d2d)]"><Landmark className="text-[#8bc0a8]" size={28} /><h2 className="mt-2 font-[Syne] text-2xl font-bold">The numbers<br />have a pulse.</h2><p className="mt-2 text-xs leading-5 text-[#a6b8b0]">Cash {money(state.money)} · debt {money(state.debt)} · inflation {state.inflation.toFixed(1)}%</p></Panel><Panel><SectionTitle>Dashboard</SectionTitle><Metric label="bank balance" value={money(state.bankBalance)} color="#91c9a3" /><div className="mt-4"><Metric label="portfolio" value={money(state.portfolio)} color="#c4a36c" /></div><div className="mt-4"><Metric label="crypto exposure" value={state.cryptoExposure} color="#b58cc3" /></div><div className="mt-4"><Metric label="weekly result" value={money(state.lastWeeklyIncome)} color={state.lastWeeklyIncome >= 0 ? '#91c9a3' : '#d77f89'} /></div></Panel><Panel><SectionTitle>One move</SectionTitle><Choice title="Move safe cash to an index fund" detail="A quiet long game. $180 now, modest portfolio upside." onClick={() => dispatch({ type: 'APP_LOOP', app, choice: 'invest' })} /><Choice title="Accept a volatile crypto/NFT allocation" detail="Scam exposure rises. A bad quarter can eat the rent." risk="scam risk / rug-pull" onClick={() => dispatch({ type: 'APP_LOOP', app, choice: 'night' })} /><Choice title="Build a cash buffer" detail="Take a smaller win and protect next week's rent." onClick={() => dispatch({ type: 'APP_LOOP', app, choice: 'save' })} /></Panel></Shell>; }

function Studio({ onBack }: { onBack: () => void }) { const { state, dispatch } = useGame(); return <Shell title="Studio" subtitle="casting / streaming wars" onBack={onBack}><Panel><SectionTitle>Open offers <span className="text-[#f6b954]">• {state.contractOffers}</span></SectionTitle><Choice title="Glass Houses / NetStream" detail="$2,400 + 4 backend points / director politics are calm." onClick={() => dispatch({ type: 'NEGOTIATE', push: 2 })} /><Choice title="Neon Saints / MaxPlus" detail="$900 + exposure / stunt clause requires a real decision." risk="health / insurance" onClick={() => dispatch({ type: 'STUNT', accept: true })} /><Choice title="Keep the boundary" detail="Refuse unsafe work. You may lose the role, not the shoulder." onClick={() => dispatch({ type: 'STUNT', accept: false })} /></Panel><Panel><SectionTitle>Career pulse</SectionTitle><div className="grid grid-cols-3 gap-2 text-center"><div className="rounded-xl bg-[#20243a] p-3"><Film size={16} className="mx-auto mb-2 text-[#cf9c5c]" /><strong className="block font-[Syne] text-lg">{state.movies}</strong><span className="text-[9px] text-[#868b9c]">films</span></div><div className="rounded-xl bg-[#20243a] p-3"><Star size={16} className="mx-auto mb-2 text-[#f6b954]" /><strong className="block font-[Syne] text-lg">{state.backendPoints}</strong><span className="text-[9px] text-[#868b9c]">backend pts</span></div><div className="rounded-xl bg-[#20243a] p-3"><Play size={16} className="mx-auto mb-2 text-[#8db0b9]" /><strong className="block font-[Syne] text-lg">{state.streamingDeals.length}</strong><span className="text-[9px] text-[#868b9c]">deals</span></div></div></Panel></Shell>; }

function CareerApp({ onBack }: { onBack: () => void }) { const { state, dispatch } = useGame(); const meta = apps.find(a => a.id === state.activeApp)!; return <Shell title={meta.name} subtitle="career desk / strategic relevance" onBack={onBack}><Panel><meta.icon className="text-[#d5a66f]" size={29} /><h2 className="mt-2 font-[Syne] text-2xl font-bold">{meta.name === 'Boxing Night' ? 'A clean spectacle.' : 'The next yes has terms.'}</h2><p className="mt-2 text-xs leading-5 text-[#a9a7aa]">Streaming wars reward leverage, not just talent. Every public win can create a private cost.</p></Panel><Panel><SectionTitle>Available moves</SectionTitle><Choice title={meta.name === 'Boxing Night' ? 'Take the main event' : 'Accept the offer'} detail="Cash, reach, and a new audience. The body and reputation carry the invoice." risk={meta.name === 'Boxing Night' ? 'injury / loss on record' : 'NDA / schedule pressure'} onClick={() => dispatch({ type: 'APP_LOOP', app: state.activeApp, choice: meta.name === 'Boxing Night' ? 'night' : 'accept' })} /><Choice title="Hold for better leverage" detail="Wait one week. Rent still arrives while the room decides." onClick={() => dispatch({ type: 'APP_LOOP', app: state.activeApp, choice: 'pause' })} /><Choice title="Decline with grace" detail="Protect the brand and leave a clean line back in." onClick={() => dispatch({ type: 'APP_LOOP', app: state.activeApp, choice: 'decline' })} /></Panel></Shell>; }

function RiskApp({ onBack }: { onBack: () => void }) { const { state, dispatch } = useGame(); const meta = apps.find(a => a.id === state.activeApp)!; const special = meta.id === 'prcommand' ? 'crisis desk' : meta.id === 'deepfakedesk' ? 'synthetic media response' : meta.id === 'swatshield' ? 'fictional safety layer' : 'controlled consequences'; return <Shell title={meta.name} subtitle={special} onBack={onBack}><Panel className="border-[#a65f78]/30 bg-[#2b2034]"><meta.icon className="text-[#d990ad]" size={29} /><h2 className="mt-2 font-[Syne] text-2xl font-bold">{meta.id === 'prcommand' ? 'Make the room safer.' : 'Risk has a dashboard.'}</h2><p className="mt-3 text-xs leading-5 text-[#b7a7b7]">Fictional game mechanics only. No real-world tactics, services, or instructions are provided.</p></Panel><Panel><SectionTitle>Choose a response</SectionTitle><Choice title={meta.id === 'prcommand' ? 'Hire crisis PR' : 'Report and correct'} detail={`PR credits ${state.prCredits} · legal heat ${state.legalHeat}% · deepfake exposure ${state.deepfakeExposure}%`} onClick={() => dispatch({ type: 'APP_LOOP', app: state.activeApp, choice: 'report' })} /><Choice title={meta.id === 'swatshield' ? 'Activate protection layer' : 'Spend on a quiet reset'} detail="A costly, boring move that protects the next week." risk="cash cost / slower growth" onClick={() => dispatch({ type: 'APP_LOOP', app: state.activeApp, choice: 'block' })} /><Choice title="Feed the machine" detail="Buy fictional algorithmic reach. The number rises; trust may not." risk="bot spend / authenticity" onClick={() => dispatch({ type: 'APP_LOOP', app: state.activeApp, choice: 'night' })} /></Panel><Panel><Metric label="burnout" value={state.burnout} color="#d77f89" /><div className="mt-4"><Metric label="swat risk" value={state.swatRisk} color="#d49c76" /></div></Panel></Shell>; }

function AppDetail({ onBack, meta }: { onBack: () => void; meta: AppMeta }) { const { state, dispatch } = useGame(); return <Shell title={meta.name} subtitle={`${meta.note} / live service`} onBack={onBack}><Panel className="bg-[linear-gradient(145deg,#2e3044,#191c2b)]"><meta.icon size={30} style={{ color: meta.color }} /><h2 className="mt-3 font-[Syne] text-2xl font-bold">{meta.name} is online.</h2><p className="mt-2 text-xs leading-5 text-[#a8acb7]">A small decision now changes the weekly report. Nothing here is a free win.</p></Panel><Panel><SectionTitle>Available actions</SectionTitle><Choice title="Make the move" detail="Build signal and take a measured risk." onClick={() => dispatch({ type: 'APP_LOOP', app: meta.id, choice: 'publish' })} /><Choice title="Protect the week" detail="Spend a little to preserve health, privacy, or cashflow." onClick={() => dispatch({ type: 'APP_LOOP', app: meta.id, choice: 'pause' })} /><Choice title="Take the night shift" detail="Reach spikes. So does the pressure." risk="stress / paparazzi pressure" onClick={() => dispatch({ type: 'APP_LOOP', app: meta.id, choice: 'night' })} /></Panel><Panel><SectionTitle>OS telemetry</SectionTitle><div className="grid grid-cols-2 gap-3"><Metric label="reputation" value={state.reputation} color="#c8a0da" /><Metric label="health" value={state.health} color="#78b9a1" /></div><p className="mt-4 border-t border-white/[.07] pt-4 text-xs leading-5 text-[#858b9d]">{state.eventLog[0]}</p></Panel></Shell>; }

export default App;