import { useState, type ReactNode } from 'react';
import { GameProvider, useGame, type AppName } from './state/game';
import { AppHeader, Button, Choice, Metric, Modal, Panel, SectionTitle } from './components/primitives';
import { Activity, Aperture, ArrowUpRight, Award, Baby, Banknote, BriefcaseBusiness, Building2, Camera, Clapperboard, Crown, Gavel, Heart, House, Landmark, LockKeyhole, MapPin, Megaphone, Play, ScanFace, Shield, Sparkles, Star, Sword, TrendingUp, UserRound, Users, Video, WandSparkles, WalletCards, Youtube, Zap } from 'lucide-react';

const money = (n: number) => `$${Math.max(0, n).toLocaleString()}`;
const apps: { id: AppName; name: string; note: string; icon: typeof Star; color: string; locked?: boolean }[] = [
  { id: 'instafame', name: 'InstaFame', note: 'social', icon: Camera, color: '#c46d78' },
  { id: 'viewtube', name: 'ViewTube', note: 'video', icon: Youtube, color: '#a94d5b' },
  { id: 'chirp', name: 'Chirp', note: 'hot takes', icon: Megaphone, color: '#7680bc' },
  { id: 'reeltok', name: 'ReelTok', note: 'trends', icon: Activity, color: '#57a1a2' },
  { id: 'studio', name: 'Studio', note: 'career', icon: Clapperboard, color: '#c39155' },
  { id: 'jetsetter', name: 'JetSetter', note: 'travel', icon: MapPin, color: '#628ca1' },
  { id: 'bizmogul', name: 'BizMogul', note: 'ventures', icon: TrendingUp, color: '#8a6fa8' },
  { id: 'oscaraura', name: 'OscarAura', note: 'awards', icon: Award, color: '#bc9851' },
  { id: 'justilaw', name: 'JustiLaw', note: 'legal', icon: Gavel, color: '#64728d' },
  { id: 'darkos', name: 'DarkOS', note: 'fictional', icon: LockKeyhole, color: '#684f6c' },
  { id: 'glowclinic', name: 'GlowClinic', note: 'appearance', icon: ScanFace, color: '#bc6d88' },
  { id: 'rayamatch', name: 'RayaMatch', note: 'romance', icon: Heart, color: '#a45b76' },
  { id: 'billionestate', name: 'BillionEstate', note: 'security', icon: Building2, color: '#7d7770' },
  { id: 'fanpulse', name: 'FanPulse', note: 'community', icon: Users, color: '#5e8194' },
];

function App() { return <GameProvider><StarLife /></GameProvider>; }

function StarLife() {
  const { state, dispatch } = useGame();
  const go = (app: AppName) => dispatch({ type: 'OPEN_APP', app });
  return <main className="star-app phone-noise text-[#eee6d7]"><div className="phone-frame"><div className="phone-inner">
    {state.activeApp === 'home' ? <Home /> : <AppView />}
    {state.modal && <Modal {...state.modal} onClose={() => dispatch({ type: 'CLOSE_MODAL' })} onPrimary={state.modal.onPrimary ? () => { state.modal?.onPrimary && dispatch(state.modal.onPrimary); dispatch({ type: 'CLOSE_MODAL' }); } : undefined} onSecondary={state.modal.onSecondary ? () => { state.modal?.onSecondary && dispatch(state.modal.onSecondary); dispatch({ type: 'CLOSE_MODAL' }); } : undefined} />}
  </div></div></main>;

  function Home() {
    const [showProfile, setShowProfile] = useState(false);
    return <div className="min-h-full bg-[linear-gradient(180deg,#121526_0%,#0e101c_100%)] pb-4">
      <StatusBar />
      <div className="px-5 pt-3">
        <div className="flex items-start justify-between"><div><p className="mono text-[10px] uppercase tracking-[.2em] text-[#8d92a4]">Star Life / week {state.week}</p><h1 className="mt-1 font-[Syne] text-3xl font-bold tracking-[-.04em]">Make them<br /><span className="text-[#f6b954]">remember you.</span></h1></div><button onClick={() => setShowProfile(!showProfile)} data-testid="button-open-profile" className="grid h-11 w-11 place-items-center rounded-full border border-[#f6b954]/30 bg-[#2b2b40] text-[#f6b954]"><UserRound size={19} /></button></div>
        {showProfile && <Panel className="animate-rise mt-4"><SectionTitle>Player dossier</SectionTitle><div className="grid grid-cols-3 gap-2 text-center"><div><strong className="block font-[Syne] text-lg">{state.age}</strong><span className="text-[10px] text-[#9297a8]">years old</span></div><div><strong className="block font-[Syne] text-lg">{state.tier}</strong><span className="text-[10px] text-[#9297a8]">tier</span></div><div><strong className="block font-[Syne] text-lg">{state.city}</strong><span className="text-[10px] text-[#9297a8]">base</span></div></div></Panel>}
        <div className="mt-7 grid grid-cols-3 gap-2"><TopStat label="CASH" value={money(state.money)} color="#f6b954" /><TopStat label="FAME" value={`${state.fame}`} color="#db7b86" /><TopStat label="REACH" value={compact(state.followers)} color="#81b8b0" /></div>
        <div className="mt-3 grid grid-cols-2 gap-3"><Metric label="Reputation" value={state.reputation} color="#c8a0da" /><Metric label="Health" value={state.health} color="#78b9a1" /></div>
      </div>
      <div className="mt-7 px-5"><SectionTitle>Open orbit</SectionTitle><div className="grid grid-cols-4 gap-x-2 gap-y-5">{apps.map((a, i) => <button key={a.id} onClick={() => go(a.id)} data-testid={`button-open-${a.id}`} className={`animate-rise delay-${Math.min(i % 4, 3)} group text-center`}><span className="mx-auto grid h-[52px] w-[52px] place-items-center rounded-[17px] border border-white/10 shadow-lg transition-transform group-active:scale-95" style={{ background: `linear-gradient(145deg, ${a.color}, #24263a)` }}><a.icon size={22} strokeWidth={1.7} /></span><span className="mt-2 block text-[11px] font-medium text-[#dbd7d1]">{a.name}</span><span className="mt-0.5 block mono text-[8px] uppercase tracking-wider text-[#6f7488]">{a.note}</span></button>)}</div></div>
      <div className="mt-7 px-5"><SectionTitle action={<span className="mono text-[9px] text-[#696f80]">LIVE FEED</span>}>Signal</SectionTitle><div className="scan-line overflow-hidden rounded-xl border border-white/[.07] bg-[#181b2b] p-3"><p className="flex gap-2 text-xs leading-5 text-[#b7bac6]"><Zap size={14} className="mt-0.5 shrink-0 text-[#f6b954]" />{state.eventLog[0]}</p></div></div>
      <div className="mt-7 px-5"><Button className="flex w-full items-center justify-center gap-2 py-4 text-base" onClick={() => dispatch({ type: 'ADVANCE_WEEK' })} data-testid="button-advance-week"><span>Advance week</span><ArrowUpRight size={18} /></Button><p className="mt-2 text-center mono text-[9px] uppercase tracking-[.16em] text-[#646a7c]">one tap • consequences compound</p></div>
      <div className="mt-7 grid grid-cols-4 border-t border-white/[.07] px-7 pt-4 text-center"><Dock icon={WalletCards} label="Money" value={money(state.money)} /><Dock icon={Crown} label="Tier" value={state.tier} /><Dock icon={Shield} label="Risk" value={`${state.cancelHeat}%`} /><Dock icon={House} label="Home" value={state.city} /></div>
    </div>;
  }

  function StatusBar() { return <div className="flex items-center justify-between px-5 pt-4 text-[10px] text-[#c1c0c0]"><span className="mono">09:41</span><span className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#f6b954]" />ST★R LIFE <span className="mono">▮▮▮</span></span></div>; }
  function AppView() { const common = { onBack: () => dispatch({ type: 'BACK_HOME' }) }; switch (state.activeApp) { case 'instafame': return <InstaFame {...common} />; case 'viewtube': return <ViewTube {...common} />; case 'chirp': return <Chirp {...common} />; case 'reeltok': return <ReelTok {...common} />; case 'studio': return <Studio {...common} />; case 'jetsetter': return <JetSetter {...common} />; case 'bizmogul': return <BizMogul {...common} />; case 'oscaraura': return <OscarAura {...common} />; case 'justilaw': return <JustiLaw {...common} />; case 'darkos': return <DarkOS {...common} />; case 'glowclinic': return <GlowClinic {...common} />; case 'rayamatch': return <RayaMatch {...common} />; case 'billionestate': return <BillionEstate {...common} />; case 'fanpulse': return <FanPulse {...common} />; default: return null; } }
}

function compact(n: number) { return n > 999999 ? `${(n / 1000000).toFixed(1)}M` : n > 999 ? `${(n / 1000).toFixed(1)}K` : n.toString(); }
function TopStat({ label, value, color }: { label: string; value: string; color: string }) { return <div className="rounded-xl border border-white/[.07] bg-[#1a1d2d] px-3 py-2"><span className="mono text-[8px] tracking-[.16em] text-[#7c8191]">{label}</span><strong className="mt-1 block font-[Syne] text-lg" style={{ color }}>{value}</strong></div>; }
function Dock({ icon: Icon, label, value }: { icon: typeof Star; label: string; value: string }) { return <div><Icon size={15} className="mx-auto mb-1 text-[#777d92]" /><span className="block text-[10px] text-[#828697]">{label}</span><span className="mt-0.5 block truncate px-1 mono text-[9px] text-[#d9c08b]">{value}</span></div>; }
function Shell({ title, subtitle, children, onBack }: { title: string; subtitle: string; children: ReactNode; onBack?: () => void }) { const { dispatch } = useGame(); return <div className="min-h-full bg-[#111322] pb-8"><Status /><AppHeader title={title} subtitle={subtitle} onBack={onBack ?? (() => dispatch({ type: 'BACK_HOME' }))} /><div className="space-y-4 px-5">{children}</div></div>; }
function Status() { const { state } = useGame(); return <div className="flex items-center justify-between px-5 pt-4"><span className="mono text-[9px] text-[#858a9b]">STAR LIFE / {state.city.toUpperCase()}</span><span className="flex items-center gap-1 mono text-[9px] text-[#f6b954]">{money(state.money)} <span className="text-[#6d7384]">•</span> W{state.week}</span></div>; }
function DispatchModal({ title, body, risk, primary, secondary, action, secondaryAction }: { title: string; body: string; risk?: string; primary: string; secondary?: string; action: any; secondaryAction?: any }) { const { dispatch } = useGame(); return <Button onClick={() => dispatch({ type: 'MODAL', modal: { title, body, risk, primary, secondary, onPrimary: action, onSecondary: secondaryAction } })} data-testid={`button-${title.toLowerCase().replaceAll(' ', '-')}`}>{primary}</Button>; }

function InstaFame({ onBack }: { onBack: () => void }) { const { state, dispatch } = useGame(); const [tab, setTab] = useState('create'); return <Shell title="InstaFame" subtitle="public image / private cost" onBack={onBack}><div className="flex gap-2 border-b border-white/[.07]">{['create', 'deals', 'audience'].map(t => <button key={t} onClick={() => setTab(t)} data-testid={`button-tab-${t}`} className={`pb-3 text-xs capitalize ${tab === t ? 'border-b-2 border-[#f6b954] text-[#f6b954]' : 'text-[#777d8d]'}`}>{t}</button>)}</div>{tab === 'create' && <><Panel className="bg-[linear-gradient(145deg,#3e2737,#1d2035)]"><div className="flex items-end justify-between"><div><span className="mono text-[9px] uppercase tracking-wider text-[#c48a98]">story camera</span><h2 className="mt-2 font-[Syne] text-2xl font-bold">Show them<br />the in-between.</h2></div><Camera size={42} strokeWidth={1} className="text-[#e4a0a5]" /></div><Button className="mt-5 w-full" onClick={() => dispatch({ type: 'POST_STORY' })} data-testid="button-post-story">Post story <span className="ml-2 text-xs opacity-60">expires in 1 week</span></Button></Panel><Panel><SectionTitle>Choose your signal</SectionTitle><Choice title="A candid studio morning" detail="Builds trust with a smaller, warmer audience." onClick={() => dispatch({ type: 'POST_FEED', kind: 'honest' })} /><Choice title="The impossible mirror shot" detail="High reach, high expectation. Your image becomes the story." onClick={() => dispatch({ type: 'POST_FEED', kind: 'thirst trap' })} risk="pressure +3" /></Panel></>}{tab === 'deals' && <Panel><SectionTitle>Inbox / paid offers</SectionTitle><Choice title="NOIR / perfume" detail="A quiet luxury scent. $850 today." onClick={() => dispatch({ type: 'BRAND_DEAL', brand: 'Perfume' })} /><Choice title="VOLT / crypto wallet" detail="$2,200 wire. No disclosure in the brief." risk="scam risk / reputation -17" onClick={() => dispatch({ type: 'BRAND_DEAL', brand: 'Crypto wallet' })} /><Choice title="Morrow / detox tea" detail="$460 and a three-post commitment." risk="health claims" onClick={() => dispatch({ type: 'BRAND_DEAL', brand: 'Detox tea' })} /></Panel>}{tab === 'audience' && <Panel><SectionTitle>Follower demographics</SectionTitle><Metric label="Women 18–24" value={62} color="#e3a36f" /><div className="mt-4"><Metric label="Men 25–34" value={24} color="#84a6bf" /></div><div className="mt-4"><Metric label="Creative cities" value={38} color="#c995c8" /></div><p className="mt-5 border-t border-white/[.07] pt-4 text-xs leading-5 text-[#969aaa]">Your audience wants proximity, not polish. Stories are outperforming feed posts by 1.8×.</p></Panel>}</Shell>; }

function ViewTube({ onBack }: { onBack: () => void }) { const { dispatch, state } = useGame(); return <Shell title="ViewTube" subtitle="broadcast control room" onBack={onBack}><Panel className="bg-[linear-gradient(145deg,#332332,#1a1d2e)]"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#b45061]"><Play size={19} fill="currentColor" /></span><div><h2 className="font-[Syne] text-xl font-bold">Channel: you, uncut</h2><p className="text-xs text-[#a8a0a7]">{compact(state.followers)} subscribers / {money(state.adsense)} weekly ads</p></div></div><div className="mt-5 grid grid-cols-2 gap-2"><Button onClick={() => dispatch({ type: 'UPLOAD', mode: 'safe' })} data-testid="button-upload-safe">Upload rehearsal</Button><Button variant="dark" onClick={() => dispatch({ type: 'UPLOAD', mode: 'raw' })} data-testid="button-upload-raw">Go unfiltered</Button></div></Panel><Panel><SectionTitle>Monetization monitor</SectionTitle><div className="flex items-center justify-between border-b border-white/[.07] pb-3"><span className="text-xs text-[#aeb1bb]">Daily AdSense</span><strong className="mono text-[#f6b954]">{money(state.adsense)}</strong></div><Choice title="Cancellation protocol" detail="The internet thinks your last video crossed a line. Record an apology." onClick={() => dispatch({ type: 'MODAL', modal: { title: 'The apology cut', body: 'You have one take. Authenticity may protect your reputation; performance will protect your reach.', risk: 'fake tears increase cancel heat', primary: 'Speak plainly', secondary: 'Turn it on', onPrimary: { type: 'APOLOGY', fake: false }, onSecondary: { type: 'APOLOGY', fake: true } } })} /></Panel></Shell>; }

function Chirp({ onBack }: { onBack: () => void }) { const { dispatch } = useGame(); return <Shell title="Chirp" subtitle="the blue room / volatile" onBack={onBack}><Panel><div className="flex items-start justify-between"><div><span className="mono text-[9px] uppercase tracking-widest text-[#7d85bc]">Now trending</span><h2 className="mt-2 font-[Syne] text-2xl font-bold">Everyone has<br />a receipt.</h2></div><Megaphone className="text-[#7884c0]" size={38} strokeWidth={1} /></div><p className="mt-4 text-xs leading-5 text-[#a0a4b3]">A rival's new campaign just passed yours. You could say nothing. Or give the timeline a villain.</p></Panel><Panel><SectionTitle>Tag a rival</SectionTitle><Choice title="@sloanevale / 4.2M" detail="“Some people confuse visibility with a career.”" risk="beef / stress +14" onClick={() => dispatch({ type: 'BEEF', rival: 'Sloane Vale' })} /><Choice title="@nico_saint / 8.7M" detail="A protected brand. The legal team is fast." risk="high retaliation" onClick={() => dispatch({ type: 'BEEF', rival: 'Nico Saint' })} /><div className="mt-3 flex items-center gap-2 rounded-lg bg-[#20243a] p-3 text-xs text-[#9fa3b3]"><Sparkles size={14} className="text-[#f6b954]" /> Supportive comments are temporary. Toxic ones screenshot forever.</div></Panel></Shell>; }

function ReelTok({ onBack }: { onBack: () => void }) { const { dispatch, state } = useGame(); return <Shell title="ReelTok" subtitle="trend desk / live" onBack={onBack}><Panel className="bg-[linear-gradient(145deg,#18333b,#1a1c2b)]"><span className="mono text-[9px] uppercase tracking-widest text-[#82c0bd]">Trend window / 02:18 remaining</span><h2 className="mt-2 font-[Syne] text-2xl font-bold">Borrow the moment.</h2><p className="mt-2 text-xs leading-5 text-[#a7b1b5]">The feed is rewarding risk today. Your age is visible; your timing is not.</p></Panel><Panel><SectionTitle>Choose a format</SectionTitle><Choice title="The Lowlight Dance" detail="A precise eight-count with a chance to reach 40K new eyes." onClick={() => dispatch({ type: 'TREND', kind: 'dance' })} /><Choice title="Prank your casting agent" detail="Chaotic, human, and one bad reaction away from a crisis." risk="reputation / legal" onClick={() => dispatch({ type: 'TREND', kind: 'prank' })} /><p className="mt-3 text-[10px] text-[#777d8d]">Age signal: {state.age}. Older players can be called cringe by the feed.</p></Panel></Shell>; }

function Studio({ onBack }: { onBack: () => void }) { const { state, dispatch } = useGame(); return <Shell title="Studio" subtitle="casting / your next yes" onBack={onBack}><Panel><SectionTitle>Open auditions <span className="text-[#f6b954]">• 3</span></SectionTitle><Choice title="Glass Houses" detail="Indie thriller / Mara Quinn, director / $2,400" onClick={() => dispatch({ type: 'MODAL', modal: { title: 'Contract negotiation', body: 'Mara Quinn likes your read. Negotiate the upfront fee and backend. Push too hard and this offer disappears.', risk: 'director patience / moderate', primary: 'Ask for more', secondary: 'Sign clean', onPrimary: { type: 'NEGOTIATE', push: 2 }, onSecondary: { type: 'NEGOTIATE', push: 1 } } })} /><Choice title="Neon Saints" detail="Streaming action / $900 + exposure / stunt required" risk="health / dangerous stunt" onClick={() => dispatch({ type: 'MODAL', modal: { title: 'The stunt clause', body: 'The director wants you to do the rooftop drop yourself. No harness in the final frame.', risk: 'health damage / career acceleration', primary: 'Take the stunt', secondary: 'Refuse it', onPrimary: { type: 'STUNT', accept: true }, onSecondary: { type: 'STUNT', accept: false } } })} /></Panel><Panel><SectionTitle>Career pulse</SectionTitle><div className="grid grid-cols-3 gap-2 text-center"><div className="rounded-xl bg-[#20243a] p-3"><Clapperboard size={16} className="mx-auto mb-2 text-[#cf9c5c]" /><strong className="block font-[Syne] text-lg">{state.movies}</strong><span className="text-[9px] text-[#868b9c]">films</span></div><div className="rounded-xl bg-[#20243a] p-3"><Star size={16} className="mx-auto mb-2 text-[#f6b954]" /><strong className="block font-[Syne] text-lg">{state.fame}</strong><span className="text-[9px] text-[#868b9c]">fame</span></div><div className="rounded-xl bg-[#20243a] p-3"><BriefcaseBusiness size={16} className="mx-auto mb-2 text-[#8db0b9]" /><strong className="block font-[Syne] text-lg">{state.tier}</strong><span className="text-[9px] text-[#868b9c]">tier</span></div></div></Panel></Shell>; }

function JetSetter({ onBack }: { onBack: () => void }) { const { state, dispatch } = useGame(); const cities = ['Los Angeles', 'New York', 'London', 'Tokyo', 'Paris']; return <Shell title="JetSetter" subtitle="global casting board" onBack={onBack}><Panel className="bg-[linear-gradient(145deg,#263a49,#1a1d2c)]"><MapPin size={25} className="text-[#8ebdca]" /><h2 className="mt-3 font-[Syne] text-2xl font-bold">Your orbit<br />is getting wider.</h2><p className="mt-2 text-xs text-[#a5afb4]">Every city has a different price for being seen.</p></Panel><Panel><SectionTitle>Choose a base</SectionTitle>{cities.map(city => <Choice key={city} title={city} detail={city === state.city ? 'Current base / no flight required' : `${city === 'Tokyo' || city === 'Paris' ? '$420' : '$230'} flight / local audition board`} onClick={() => dispatch({ type: 'TRAVEL', city })} disabled={city === state.city} risk={city === 'New York' ? 'paparazzi aggression / high' : undefined} />)}</Panel></Shell>; }

function BizMogul({ onBack }: { onBack: () => void }) { const { state, dispatch } = useGame(); const [quality, setQuality] = useState(78); const [kind, setKind] = useState('fashion line'); const wealthy = state.money >= 3200; return <Shell title="BizMogul" subtitle="your name / a product"><Panel className="bg-[linear-gradient(145deg,#322d43,#1b1d2e)]"><span className="mono text-[9px] uppercase tracking-widest text-[#bd9bd1]">Founder mode</span><h2 className="mt-2 font-[Syne] text-2xl font-bold">Turn attention<br />into inventory.</h2><p className="mt-2 text-xs text-[#aaa6b4]">Capital required: {money(3200)}. You have {money(state.money)}.</p></Panel><Panel><SectionTitle>Build brief</SectionTitle><div className="flex gap-2">{['fashion line', 'makeup brand', 'tequila company'].map(k => <button key={k} onClick={() => setKind(k)} data-testid={`button-product-${k}`} className={`rounded-lg px-2 py-2 text-[10px] capitalize ${kind === k ? 'bg-[#bd9bd1] text-[#1a1a25]' : 'bg-[#25283c] text-[#9da1b1]'}`}>{k}</button>)}</div><div className="mt-5"><div className="mb-2 flex justify-between text-xs"><span>Quality budget</span><strong className="mono text-[#bd9bd1]">{quality}%</strong></div><input aria-label="quality" data-testid="input-quality" type="range" min="20" max="100" value={quality} onChange={e => setQuality(Number(e.target.value))} className="w-full accent-[#bd9bd1]" /></div><Button className="mt-5 w-full" disabled={!wealthy} onClick={() => dispatch({ type: 'LAUNCH_BIZ', kind, quality })} data-testid="button-launch-business">{wealthy ? 'Launch venture' : 'Need more capital'}</Button></Panel></Shell>; }

function OscarAura({ onBack }: { onBack: () => void }) { const { state, dispatch } = useGame(); const [outfit, setOutfit] = useState(18000); return <Shell title="OscarAura" subtitle="annual awards / week {52 - (state.week % 52)}"><Panel className="bg-[linear-gradient(145deg,#473b27,#1d1d2d)]"><Award size={28} className="text-[#f6b954]" /><h2 className="mt-2 font-[Syne] text-2xl font-bold">{state.nominated ? 'The envelope has your name.' : 'Build the case.'}</h2><p className="mt-2 text-xs leading-5 text-[#b6ad9d]">Nominations draw from films, album sales, and a little well-placed hype.</p></Panel><Panel><SectionTitle>Red carpet calculator</SectionTitle><div className="flex items-center justify-between text-xs"><span>Stylist budget</span><strong className="mono text-[#f6b954]">{money(outfit)}</strong></div><input aria-label="stylist budget" data-testid="input-outfit-budget" type="range" min="0" max="50000" step="5000" value={outfit} onChange={e => setOutfit(Number(e.target.value))} className="mt-4 w-full accent-[#f6b954]" /><div className="mt-4 grid grid-cols-3 gap-2 text-center text-[10px] text-[#8f94a4]"><span>borrowed<br /><b className="text-[#d9d2c2]">$0</b></span><span>custom<br /><b className="text-[#d9d2c2]">$25K</b></span><span>archive<br /><b className="text-[#d9d2c2]">$50K</b></span></div><Button className="mt-5 w-full" onClick={() => dispatch({ type: 'OSCAR', outfit })} data-testid="button-walk-red-carpet">Walk the carpet</Button></Panel></Shell>; }

function JustiLaw({ onBack }: { onBack: () => void }) { const { state, dispatch } = useGame(); return <Shell title="JustiLaw" subtitle="risk management / live"><Panel className="border-[#b65f69]/30 bg-[#2c202d]"><div className="flex items-center gap-3"><Gavel className="text-[#d77f89]" /><div><span className="mono text-[9px] uppercase tracking-widest text-[#d77f89]">Current status</span><h2 className="mt-1 font-[Syne] text-lg font-bold">{state.legalStatus}</h2></div></div><p className="mt-4 text-xs leading-5 text-[#c0abb1]">Stress and scandal create legal gravity. Document everything.</p></Panel><Panel><SectionTitle>Open incidents</SectionTitle><Choice title="Paparazzi confrontation" detail="A camera got too close outside the club. Your security team is waiting." risk="reputation / arrest risk" onClick={() => dispatch({ type: 'LAW', choice: 'lawyer' })} /><Choice title="DUI / arrest risk" detail="You can represent yourself, or pay for someone who knows the judge." risk="prison / fame reset" onClick={() => dispatch({ type: 'LAW', choice: 'self' })} /></Panel><Panel><Metric label="Stress exposure" value={state.stress} color="#d77f89" /><div className="mt-4"><Metric label="Cancel heat" value={state.cancelHeat} color="#e39375" /></div></Panel></Shell>; }

function DarkOS({ onBack }: { onBack: () => void }) { const { dispatch } = useGame(); return <Shell title="DarkOS" subtitle="fictional underworld / unsafe"><Panel className="border-[#79577d]/40 bg-[linear-gradient(145deg,#2b2035,#161827)]"><div className="flex items-center gap-2 text-[#d49bd8]"><LockKeyhole size={18} /><span className="mono text-[9px] uppercase tracking-widest">fictional system</span></div><h2 className="mt-3 font-[Syne] text-2xl font-bold">Nothing here<br />is consequence-free.</h2><p className="mt-3 text-xs leading-5 text-[#b3a5b7]">These choices are fictional game mechanics about reputation and risk. No real-world instructions or services are provided.</p></Panel><Panel><Choice title="Ruin a rival's career" detail="Seed a fictional dossier into the trade press." risk="legal status / stress / reputation" onClick={() => dispatch({ type: 'DARKOS', choice: 'dossier' })} /><Choice title="Leak a fake scandal" detail="A fabricated story, designed to be believed for one news cycle." risk="high cancel heat" onClick={() => dispatch({ type: 'DARKOS', choice: 'leak' })} /><Choice title="Buy illegal stamina booster" detail="A fictional black-market upgrade with a brutal health cost." risk="health / investigation" onClick={() => dispatch({ type: 'DARKOS', choice: 'booster' })} /></Panel></Shell>; }

function GlowClinic({ onBack }: { onBack: () => void }) { const { state, dispatch } = useGame(); return <Shell title="GlowClinic" subtitle="appearance engineering"><Panel className="bg-[linear-gradient(145deg,#432c3e,#1c1d2d)]"><ScanFace className="text-[#de8ca9]" size={28} /><h2 className="mt-2 font-[Syne] text-2xl font-bold">Looks are leverage.</h2><div className="mt-4"><Metric label="Current look score" value={state.looks} color="#de8ca9" /></div></Panel><Panel><SectionTitle>Upgrade menu</SectionTitle><Choice title="Micro refresh" detail="$1,000 / subtle, low recovery" onClick={() => dispatch({ type: 'SURGERY', cost: 1000 })} /><Choice title="Feature edit" detail="$25,000 / visible on camera" risk="botch risk / health" onClick={() => dispatch({ type: 'SURGERY', cost: 25000 })} /><Choice title="Total transformation" detail="$100,000 / the old you becomes archival" risk="botch risk / fame volatility" onClick={() => dispatch({ type: 'SURGERY', cost: 100000 })} /></Panel></Shell>; }

function RayaMatch({ onBack }: { onBack: () => void }) { const { state, dispatch } = useGame(); const gated = ['A-List', 'Global Icon'].includes(state.tier); return <Shell title="RayaMatch" subtitle="relationships / public or private"><Panel className="bg-[linear-gradient(145deg,#442c40,#1c1d2d)]"><Heart className="text-[#db7b91]" size={27} /><h2 className="mt-2 font-[Syne] text-2xl font-bold">Who gets<br />the real you?</h2><p className="mt-2 text-xs text-[#b9a6b1]">A relationship can be a safe room, a headline, or both.</p></Panel><Panel><SectionTitle>Available connections</SectionTitle><Choice title="Normal person / no cameras" detail="A barista who thinks your tier is a train route." onClick={() => dispatch({ type: 'DATE', kind: 'private date' })} /><Choice title="Mega-celebrity / shared orbit" detail="A controlled spark with real chemistry underneath." onClick={() => dispatch({ type: 'DATE', kind: 'mega-celebrity date' })} /><Choice title="Billionaire RayaMatch" detail={gated ? 'A yacht week and a joint cover story.' : 'Unlocks at A-List.'} disabled={!gated} risk={!gated ? 'tier locked' : 'PR stunt / breakup drama'} onClick={() => dispatch({ type: 'DATE', kind: 'PR stunt' })} /></Panel></Shell>; }

function BillionEstate({ onBack }: { onBack: () => void }) { const { state, dispatch } = useGame(); return <Shell title="BillionEstate" subtitle="property / protection"><Panel className="bg-[linear-gradient(145deg,#393530,#1a1c2b)]"><Building2 className="text-[#d8b782]" size={28} /><h2 className="mt-2 font-[Syne] text-2xl font-bold">Privacy is<br />the new luxury.</h2><p className="mt-2 text-xs text-[#b2ada4]">Security is not glamour. It is what lets glamour keep happening.</p></Panel><Panel><SectionTitle>Acquire</SectionTitle><Choice title="West Hollywood penthouse" detail="$8,500 / security rating +6" onClick={() => dispatch({ type: 'ESTATE', kind: 'Penthouse' })} /><Choice title="Beverly Hills mansion" detail="$28,000 / security rating +12 / press magnet" risk="cashflow" onClick={() => dispatch({ type: 'ESTATE', kind: 'Mansion' })} /><Choice title="Hire close protection" detail="$1,400 weekly / security rating +18" onClick={() => dispatch({ type: 'BODYGUARD' })} /></Panel><Panel><Metric label="Security" value={state.security} color="#d8b782" /><div className="mt-4"><Metric label="Stalker threat" value={state.stalkerThreat} color="#da808b" /></div></Panel></Shell>; }

function FanPulse({ onBack }: { onBack: () => void }) { const { state, dispatch } = useGame(); return <Shell title="FanPulse" subtitle="community temperature"><Panel className="bg-[linear-gradient(145deg,#243941,#191d2d)]"><Users className="text-[#81bec1]" size={28} /><h2 className="mt-2 font-[Syne] text-2xl font-bold">{state.fame > 65 ? 'The crowd is close.' : 'A small room,<br />for now.'}</h2><p className="mt-3 text-xs leading-5 text-[#a6b4b4]">{state.fame > 65 ? 'Obsessive fans are starting to map your movements. One message arrived from inside your hotel.' : 'Your fans want more of your actual life. Give them a reason to stay.'}</p></Panel><Panel><SectionTitle>Overnight signal</SectionTitle><Metric label="Fan mood" value={state.fanMood} color="#81bec1" /><div className="mt-5"><Metric label="Cancel culture" value={state.cancelHeat} color="#d87d87" /></div><p className="mt-5 border-t border-white/[.07] pt-4 mono text-[10px] leading-5 text-[#7d8294]">EVENT LOG</p>{state.eventLog.slice(0, 4).map((e, i) => <p key={`${e}-${i}`} data-testid={`text-event-${i}`} className="border-b border-white/[.05] py-2 text-xs leading-5 text-[#a7aab7]">{e}</p>)}</Panel><Button variant="dark" className="w-full" onClick={() => dispatch({ type: 'ADVANCE_WEEK' })} data-testid="button-fanpulse-advance">Wait for the next signal</Button></Shell>; }

export default App;